
name: Release
on:
  release:
    types:
      - created
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false
      - name: Build and Deploy 🚀
        run: make ensure build deploy
